# Basic reference: https://www.codeproject.com/Articles/1084565/Cplusplus-Continuous-Integration-Setup
os: linux
dist: bionic
sudo: required
language: cpp
compiler:
  - clang
  - gcc

before_install:
 - sudo add-apt-repository universe
 - sudo apt update

install:
# - sudo apt-get install python-dev python-numpy
- sudo apt install libopencv-dev

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - cmake --build . --config Release -- -j2

after_success:
  - echo "Success"

after_failure:
  - echo "Failed"

notifications:
  email:
    recipients:
      - anekde@gmail.com
      - dey.sumit.kr@gmail.com
    on_success: always # default: change
    on_failure: always # default: always
